-- =============================================================================
-- AI Fast Resume — Career Agent Phase 1, Steps 1-7
--
-- Career Profile, Jobs, immutable Match Snapshots, and tailored-resume tagging
-- on resume_history. Application Tracker (applications, status history, and
-- the interview_history link) is Phase 1 Steps 8-10 and ships in a later
-- migration once that scope is approved — it is deliberately NOT in this file.
--
-- Depends on 0001_credits_and_rls.sql (resume_history must already exist).
-- Run this once against your Supabase project:
--   Dashboard -> SQL Editor -> paste -> Run
--   (or: supabase db push)
--
-- It is written to be re-runnable (idempotent).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Career Profile — one row per user.
-- -----------------------------------------------------------------------------
create table if not exists public.career_profiles (
  user_id            uuid primary key references auth.users (id) on delete cascade,
  full_name          text,
  headline           text,
  target_titles      text[] not null default '{}',
  target_locations   text[] not null default '{}',
  target_industries  text[] not null default '{}',
  seniority          text,
  work_rights        text,
  salary_min         integer,
  salary_max         integer,
  salary_currency    text,
  remote_preference  text check (remote_preference in ('remote', 'hybrid', 'onsite', 'flexible')),
  languages          text[] not null default '{}',
  -- resume_history.id is uuid in this project (that table predates the
  -- bigint-identity schema in 0001_credits_and_rls.sql — "create table if not
  -- exists" silently skipped it since it already existed). Matches reality,
  -- not the migration file's literal text.
  source_resume_id   uuid references public.resume_history (id) on delete set null,
  -- Skills the AI derived from the resume, each tagged with a confidence/source
  -- so the UI can show provenance rather than presenting guesses as fact.
  derived_skills     jsonb not null default '[]',
  -- The "fact whitelist": structured facts the user has explicitly confirmed.
  -- Downstream generation (match scoring, tailored resumes) must ground itself
  -- in this list rather than inventing experience.
  confirmed_facts    jsonb not null default '[]',
  facts_confirmed_at timestamptz,
  updated_at         timestamptz not null default now()
);

alter table public.career_profiles enable row level security;

drop policy if exists "career_profiles_own" on public.career_profiles;
create policy "career_profiles_own"
  on public.career_profiles for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- 2. Jobs — user-captured/entered job postings. Phase 1 only ever writes
--    source = 'manual' (pasted by the user); the column stays open-ended text
--    so new sources (a SEEK connector, a China platform connector, etc.) can
--    ship without a migration. Valid values are enforced in the application
--    layer (see services/career/connectors/sources.ts), not the database —
--    deliberately, so the list can grow without a schema change each time.
-- -----------------------------------------------------------------------------
create table if not exists public.jobs (
  id               bigint generated by default as identity primary key,
  user_id          uuid not null references auth.users (id) on delete cascade,
  source           text not null default 'manual',
  -- Market IS a strict enum: it drives which localization rules, resume
  -- language and compliance layer apply, and that set changes rarely and
  -- deliberately (unlike job sources, which grow continuously).
  market           text not null check (market in ('AU', 'CN')),
  source_url       text,
  title            text not null,
  company          text not null,
  location         text,
  description_text text not null,
  salary_text      text,
  employment_type  text,
  seniority        text,
  -- Reserved for future Outcome Learning (grouping applications by role
  -- cluster). Not populated or classified in Phase 1.
  job_family       text,
  posted_at        date,
  is_stale         boolean not null default false,
  raw_snapshot     jsonb,
  captured_at      timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

alter table public.jobs enable row level security;

drop policy if exists "jobs_own" on public.jobs;
create policy "jobs_own"
  on public.jobs for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- No WHERE clause: this stays a plain (non-partial) unique index on purpose.
-- Postgres already treats NULL <> NULL for uniqueness, so multiple jobs with
-- no source_url (the common case for pasted-JD manual entries) are still
-- allowed — and a plain index is required for PostgREST's upsert
-- (on_conflict=user_id,source_url) to have a matching arbiter constraint. A
-- partial index here would make every upsert fail with "no unique or
-- exclusion constraint matching the ON CONFLICT specification".
create unique index if not exists jobs_user_source_url_key
  on public.jobs (user_id, source_url);

create index if not exists jobs_user_created_idx
  on public.jobs (user_id, captured_at desc);

-- -----------------------------------------------------------------------------
-- 3. Match Snapshots — immutable. Re-scoring a job inserts a new row; there is
--    deliberately no UPDATE policy, so history can never be silently rewritten.
-- -----------------------------------------------------------------------------
create table if not exists public.match_snapshots (
  id                       bigint generated by default as identity primary key,
  user_id                  uuid not null references auth.users (id) on delete cascade,
  job_id                   bigint not null references public.jobs (id) on delete cascade,
  -- Frozen copy of the profile facts used for this score — NOT a live
  -- reference, so later profile edits never retroactively change a past
  -- match's explanation.
  career_profile_snapshot  jsonb not null,
  overall_score            numeric not null check (overall_score >= 0 and overall_score <= 100),
  -- Shape: { hardRequirements, skillsExperience, goalsPreferences,
  --          opportunityQuality, historicalOutcomes }, each { score, weight, notes }
  score_breakdown          jsonb not null,
  hard_gaps                text[] not null default '{}',
  recommended_action       text check (recommended_action in ('priority_apply', 'apply', 'consider', 'skip')),
  model_version            text,
  created_at               timestamptz not null default now()
);

alter table public.match_snapshots enable row level security;

drop policy if exists "match_snapshots_select_own" on public.match_snapshots;
create policy "match_snapshots_select_own"
  on public.match_snapshots for select using (auth.uid() = user_id);

drop policy if exists "match_snapshots_insert_own" on public.match_snapshots;
create policy "match_snapshots_insert_own"
  on public.match_snapshots for insert with check (auth.uid() = user_id);

-- No update/delete policy: a match snapshot is a permanent historical record.

create index if not exists match_snapshots_user_job_idx
  on public.match_snapshots (user_id, job_id, created_at desc);

-- -----------------------------------------------------------------------------
-- 4. resume_history extension — tag rows as base vs job-tailored instead of
--    creating a parallel "resume_versions" table. A tailored resume is just a
--    resume_history row that also happens to reference a job.
-- -----------------------------------------------------------------------------
alter table public.resume_history add column if not exists job_id bigint
  references public.jobs (id) on delete set null;
alter table public.resume_history add column if not exists variant_type text
  not null default 'base' check (variant_type in ('base', 'tailored'));

create index if not exists resume_history_user_job_idx
  on public.resume_history (user_id, job_id);

-- -----------------------------------------------------------------------------
-- Application Tracker (applications, application_status_history, and the
-- interview_history.application_id link) is Phase 1 Steps 8-10 and is not
-- part of this migration. See 0004_applications.sql.
-- -----------------------------------------------------------------------------
