-- =============================================================================
-- AI Fast Resume — Career Agent Phase 1, Steps 8-10
--
-- Tailored resumes, Application Tracker, and the Application <-> Interview
-- link. Completes the Phase 1 loop: Profile -> Job -> Match -> Tailored
-- materials -> Application -> Interview, with the data shape Outcome Learning
-- will later read.
--
-- Depends on 0002_career_agent.sql (jobs, match_snapshots).
--
-- Run once: Dashboard -> SQL Editor -> paste -> Run. Idempotent.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Tailored resumes — one job-specific resume + cover letter version.
--
-- WHY A SEPARATE TABLE (and not resume_history, as originally planned)
-- --------------------------------------------------------------------
-- public.resume_history looks like a resume store but is not one: the app
-- writes a whole-workspace snapshot into its `content` column
-- ({ resumeContent, portfolioData, careerData, interviewData, uiSettings }),
-- and the History drawer restores that snapshot wholesale. Writing per-job
-- resumes into the same table would (a) list them in the History drawer as
-- if they were restore points, since fetchHistory selects with no variant
-- filter, and (b) corrupt the editor when restored, because the restore path
-- branches on `snapshot.resumeContent` which a bare resume payload lacks.
--
-- So job-specific artifacts live here, and resume_history keeps its single
-- meaning: "a restorable snapshot of the whole workspace".
--
-- The job_id/variant_type columns added to resume_history by 0002 are now
-- unused. They are left in place rather than dropped — removing columns from
-- a live table with real user rows is a riskier operation than leaving two
-- nullable, defaulted columns unread.
-- -----------------------------------------------------------------------------
create table if not exists public.tailored_resumes (
  id           bigint generated by default as identity primary key,
  user_id      uuid   not null references auth.users (id) on delete cascade,
  job_id       bigint not null references public.jobs (id) on delete cascade,
  -- The AnalysisResult produced by the existing analyzeResume engine:
  -- { overallScore, scoreBreakdown, missingSkills, optimizedResume, ... }
  content      jsonb  not null,
  -- Denormalised out of content so the tracker can show/edit the letter
  -- without parsing the whole analysis payload.
  cover_letter text,
  model_version text,
  created_at   timestamptz not null default now()
);

alter table public.tailored_resumes enable row level security;

drop policy if exists "tailored_resumes_own" on public.tailored_resumes;
create policy "tailored_resumes_own"
  on public.tailored_resumes for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists tailored_resumes_user_job_idx
  on public.tailored_resumes (user_id, job_id, created_at desc);

-- -----------------------------------------------------------------------------
-- 2. Applications.
--
-- An application binds together one job, one immutable match snapshot, and one
-- tailored resume version — the strategy doc's rule that "投的是 A 版本，准备
-- 却用 B 版本" must be impossible. Those three references are what interview
-- prep and, later, outcome analysis read back.
--
-- No unique(user_id, job_id): re-applying to the same job after enough time has
-- passed is legitimate, so duplicate detection is a soft UI warning rather than
-- a database constraint.
-- -----------------------------------------------------------------------------
create table if not exists public.applications (
  id                 bigint generated by default as identity primary key,
  user_id            uuid not null references auth.users (id) on delete cascade,
  job_id             bigint not null references public.jobs (id) on delete cascade,
  match_snapshot_id  bigint references public.match_snapshots (id) on delete set null,
  tailored_resume_id bigint references public.tailored_resumes (id) on delete set null,
  status             text not null default 'saved'
                       check (status in ('saved', 'preparing', 'applied', 'interviewing', 'offer', 'rejected', 'withdrawn')),
  applied_via        text check (applied_via in ('extension_autofill', 'manual', 'unknown')),
  applied_at         timestamptz,
  -- Answers the user gave to application questions, kept so the same question
  -- never has to be answered twice. Shape: [{ question, answer, confirmed }]
  question_answers   jsonb not null default '[]',
  notes              text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

alter table public.applications enable row level security;

drop policy if exists "applications_own" on public.applications;
create policy "applications_own"
  on public.applications for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists applications_user_status_idx
  on public.applications (user_id, status);

create index if not exists applications_user_job_idx
  on public.applications (user_id, job_id);

-- -----------------------------------------------------------------------------
-- 3. Status history — insert-only audit trail. This is the raw material for
--    Outcome Learning later (time-to-interview, stage conversion), so rows are
--    never edited: no update policy, same reasoning as match_snapshots.
-- -----------------------------------------------------------------------------
create table if not exists public.application_status_history (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null references auth.users (id) on delete cascade,
  application_id bigint not null references public.applications (id) on delete cascade,
  status         text not null,
  note           text,
  changed_at     timestamptz not null default now()
);

alter table public.application_status_history enable row level security;

drop policy if exists "application_status_history_select_own" on public.application_status_history;
create policy "application_status_history_select_own"
  on public.application_status_history for select using (auth.uid() = user_id);

drop policy if exists "application_status_history_insert_own" on public.application_status_history;
create policy "application_status_history_insert_own"
  on public.application_status_history for insert with check (auth.uid() = user_id);

create index if not exists application_status_history_app_idx
  on public.application_status_history (application_id, changed_at);

-- -----------------------------------------------------------------------------
-- 4. interview_history extension — links a mock interview to the application it
--    was prepared for. Nullable: standalone interviews started from the
--    existing Interview module keep working unchanged.
-- -----------------------------------------------------------------------------
alter table public.interview_history add column if not exists application_id bigint
  references public.applications (id) on delete set null;

create index if not exists interview_history_application_idx
  on public.interview_history (application_id);
